#ifndef LESSONMANAGER_GLOBAL_H
#define LESSONMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LESSONMANAGER_LIBRARY)
#  define LESSONMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LESSONMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LESSONMANAGER_GLOBAL_H
