#ifndef FILEMANAGEMENT_GLOBAL_H
#define FILEMANAGEMENT_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QtPlugin>

#if defined(FILEMANAGEMENT_LIBRARY)
#  define FILEMANAGEMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILEMANAGEMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEMANAGEMENT_GLOBAL_H
