#ifndef TEXTCONTROLLER_GLOBAL_H
#define TEXTCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTCONTROLLER_LIBRARY)
#  define TEXTCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEXTCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXTCONTROLLER_GLOBAL_H
