#ifndef DEFINES_H
# define DEFINES_H

#define ORGANIZATION_NAME "Horus"
#define ORGANIZATION_DOMAIN "4--2.net"

#define SERVER_NAME "Horus Server"
#define SERVER_VERSION "0.1"

#define CLIENT_NAME "Horus Client"
#define CLIENT_VERSION "0.1"

#define DEFAULT_PLUGINS_DIRECTORY_PATH "."

#define CURRENT_PROTO_VERSION 0

#define DEFAULT_SESSION_LIFETIME 12 // in hours
#define SESSION_WORD_SIZE 128
#define SHA1_WORD_SIZE 40

#define STARTEVENTTYPE          1000
#define STOPEVENTTYPE           1001
#define LOADPLUGINEVENTTYPE     1002
#define UNLOADPLUGINEVENTTYPE   1003
#define NETWORKRECEIVEEVENTTYPE 1004

#endif // DEFINES_H
