#ifndef DEFINES_H
# define DEFINES_H

# define MODULE_NAME_SIZE 16
# define MODULE_VERSION_SIZE 8
# define MODULE_DATA_VERSION_SIZE 8
# define LOGIN_SIZE 16
# define VERSION_SIZE 8

#endif // DEFINES_H
