#ifndef ADMINISTRATION_GLOBAL_H
#define ADMINISTRATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADMINISTRATION_LIBRARY)
#  define ADMINISTRATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADMINISTRATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADMINISTRATION_GLOBAL_H
